services:
  - type: web
    name: mediasense-backend
    runtime: docker
    rootDirectory: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BACKEND_CORS_ORIGINS
        value: '["*"]'
